name: "Inspect code with ReSharper"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
      - '**/redist/*'
      - templates
      - tools
      - samples
      - docs

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install ReSharper command line tools
      run: dotnet tool install JetBrains.ReSharper.GlobalTools --global --version 2023.2.2

    - name: Build
      run: |
        dotnet restore
        dotnet build -c Debug --no-restore -p:EnforceCodeStyleInBuild=true -p:GeneratePackageOnBuild=false

    - name: Restore InspectCode cache
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/inspectcode
        key: inspectcode-${{ hashFiles('.github/workflows/resharper-inspectioncode.yaml', 'OpenMod.sln', '.editorconfig', 'OpenMod.sln.DotSettings', '**/*.csproj', '**/*.props') }}

    - name: Inspect code with ReSharper
      run: jb inspectcode OpenMod.sln --no-build --verbosity=WARN --severity=WARNING --project=OpenMod.* --exclude="unturned/OpenMod.Unturned.Module.Shared/System.Drawing/*" --caches-home=inspectcode --format=Sarif --output=results.sarif.json

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif.json
        category: resharper-inspectcode
